title: LxTechnologies Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status-lxtech.netlify.app/
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Online Server Control
      category: LxTechnologies Shards
      description: Where you can control your servers bot through a online panel.
    - name: Root Services
      category: LxTechnologies Shards
      description: This is where all the basic services are held, such as start up,
        main commands. ETC.
    - name: API
      description: How we connect our bot to other services.
      category: LxTechnologies Shards
    - name: Database
      description: Where all data on servers, users, and levels/leaderboards are held,
        alongside other data.
      category: LxTechnologies Shards
    - category: LxTechnologies Shards
      name: Configuration Services
      description: Commands/dashboard system for setup, and guild settings
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#e74a4c"
  enableLastMod: true
  headerTextColor: white
  logo: logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: false
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: LxTechnologies Shards
      untitled: true
      description: ""
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
